### ISSUE TITLE
./node_modules/.bin/standard --pretty no change

### ISSUE THREAD

**Issue by quantuminformation** [e2tox/typescript-standard#4]
I tried running `./node_modules/.bin/standard --pretty`

But no ts files where changed.

![image](https://cloud.githubusercontent.com/assets/216566/24578256/873be5b0-16d4-11e7-8e12-581ffbc819c7.png)
![image](https://cloud.githubusercontent.com/assets/216566/24578261/8d770e82-16d4-11e7-82cd-fca6acd18168.png)

I also tried to run the js `standard --fix` but that doesn't update ts files

**Comment by e2tox** [comment]
Can you provide the content of tsconfig.json file?

**Comment by e2tox** [comment]
Added support for tslint@5.0.0 
https://github.com/e2tox/typescript-standard/commit/b6aa9ed79ef2eb6500d6dfe74884e89d9a08c936
